### PR TITLE
s/ParameterMarshaler/ParameterMarshaller

### PR DESCRIPTION
**Pull request by jonlawlor**
The name of the interface was not spelled correctly.

### CODE REVIEW

**Comment by btracey** [comment]
NOT LGTM

This follows the convention in the standard library, for example, BinaryMarshaler and TextMarshaler (http://golang.org/pkg/encoding/).

**Comment by jonlawlor** [comment]
Huh, well that's surprising.  Closing.

**Comment by kortschak** [comment]
This is an ASE v BSE issue. Much as it hurts me, we write in American English.

**Comment by jonlawlor** [comment]
Ug, now I feel dense, since I am American.

**Pull request closed without merging**
