### PR TITLE
Add Students T distribution

### PR DESCRIPTION
**Pull request by btracey**

### CODE REVIEW

**Comment by kortschak** [comment]
Where are these random regressions coming from?

**Comment by btracey** [comment]
I don't know. I'm looking into it now. It seems something like sampling, but they all have a fixed seed...

**Comment by btracey** [comment]
It's partly the change to the call to quad.Fixed, but that's not a sufficient explanation.

**Comment by btracey** [comment]
I'm going to submit these two PRs and then figure out what's going on with the tests

**Pull request merged**
